services:
  db:
    image: postgres:15-alpine
    container_name: logistics_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: logistics_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d logistics_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .                   # Look at the root folder
      dockerfile: backend/Dockerfile # Use the Dockerfile inside backend
    container_name: logistics_api
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/logistics_db
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "alembic upgrade head && uvicorn backend.apis.app:app --host 0.0.0.0 --port 8000"